## Libraries

In [1]:
from datetime import date

import pandas as pd
from sqlalchemy import func, or_

from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import (
    TLS201_APPLN,               # applications
    TLS202_APPLN_TITLE,         # titles
    TLS203_APPLN_ABSTR,         # abstracts
    TLS206_PERSON,              # persons (applicants and inventors)
    TLS207_PERS_APPLN,          # person <-> application links
    TLS209_APPLN_IPC,           # IPC classification
    TLS224_APPLN_CPC,           # CPC classification
    TLS231_INPADOC_LEGAL_EVENT, # legal events
)

from epo.tipdata.patstat.database import models

In [2]:
patstat = PatstatClient()          # default: env="TEST"; use PatstatClient(env="PROD") for the full database
db = patstat.orm()                 # SQLAlchemy session used by all ORM queries below

This client instance is currently configured to use a test dataset with reduced number of publications (~10K).
Use PatstatClient(env='PROD') to use the complete PATSTAT dataset (>140M publications).
Use PatstatClient(env='TEST') to use the test dataset and avoid displaying this warning

In [3]:
FILING_YEAR = 2010

q_granted_ep = (
    db.query(
        TLS201_APPLN.appln_id,
        TLS201_APPLN.appln_auth,
        TLS201_APPLN.appln_nr,
        TLS201_APPLN.appln_kind,
        TLS201_APPLN.appln_filing_date,
    )
    .filter(
        TLS201_APPLN.appln_filing_year == FILING_YEAR,
        TLS201_APPLN.appln_auth == "EP",
        TLS201_APPLN.granted == "Y",
    )
)

patstat.df(q_granted_ep)

      appln_id appln_auth  appln_nr appln_kind appln_filing_date
0    274222610         EP  10000313         A         2010-01-14
1    274369023         EP  10000849         A         2010-01-28
2    274681480         EP  10001469         A         2010-02-12
3    274720647         EP  10001552         A         2010-02-16
4    274875659         EP  10002051         A         2010-03-01
..         ...        ...       ...        ...               ...
515  364674236         EP  10860973         A         2010-12-22
516  405968954         EP  13165754         A         2010-09-20
517  448177758         EP  16150333         A         2010-08-12
518  470108142         EP  16192322         A         2010-07-16
519  543439324         EP  20217409         A         2010-07-16

[520 rows x 5 columns]

### Example

In [3]:
FILING_YEAR = 2010

q_granted_ep = (
    db.query(
        TLS201_APPLN.appln_id,
        TLS201_APPLN.appln_auth,
        TLS201_APPLN.appln_nr,
        TLS201_APPLN.appln_kind,
        TLS201_APPLN.appln_filing_date,
    )
    .filter(
        TLS201_APPLN.appln_filing_year == FILING_YEAR,
        TLS201_APPLN.appln_auth == "EP",
        TLS201_APPLN.granted == "Y",
    )
)

patstat.df(q_granted_ep)

      appln_id appln_auth  appln_nr appln_kind appln_filing_date
0    274222610         EP  10000313         A         2010-01-14
1    274369023         EP  10000849         A         2010-01-28
2    274681480         EP  10001469         A         2010-02-12
3    274720647         EP  10001552         A         2010-02-16
4    274875659         EP  10002051         A         2010-03-01
..         ...        ...       ...        ...               ...
515  364674236         EP  10860973         A         2010-12-22
516  405968954         EP  13165754         A         2010-09-20
517  448177758         EP  16150333         A         2010-08-12
518  470108142         EP  16192322         A         2010-07-16
519  543439324         EP  20217409         A         2010-07-16

[520 rows x 5 columns]

## Patents related to the field

In [ ]:
# Keywords searched (case-insensitive) in titles and abstracts
AI_KEYWORDS = (
    "artificial intelligence",
    "neural net",
    "machine learning",
    "expert system",
    "natural language processing",
    "deep learning",
    "reinforcement learning",
    "reinforced learning",
    "learning algorithm",
    "supervised learning",
    "intelligent agent",
    "back propagation learning",
    "BP learning",
    "back propagation algorithm",
    "long short-term memory",
    "LSTM",
    "pulse coupled neural net",
    "perceptron",
    "neuro evolution",
    "liquid state machine",
    "deep belief net",
    "radial basis function net",
    "RBFNN",
    "RBF net",
    "deep net",
    "autoencoder",
    "committee machine",
    "training algorithm",
    "back propagation net",
    "BP network",
    "Q learning",
    "convolution net",
    "actor-critic algorithm",
    "feed forward net",
    "hopfield net",
    "neocognitron",
    "xgboost",
    "boltzmann machine",
    "activation function",
    "neuro dynamic programming",
    "learning model",
    "neuro computing",
    "temporal difference learning",
    "echo state net",
    "transfer learning",
    "gradient boosting",
    "adversarial learning",
    "feature learning",
    "generative adversarial net",
    "representation learning",
    "multi agent learning",
    "reservoir computing",
    "co-training",
    "probably approximate correct learning",
    "extreme learning machine",
    "ensemble learning",
    "machine intelligence",
    "neuro fuzzy",
    "lazy learning",
    "multi instance learning",
    "multi task learning",
    "computational intelligence",
    "neural model",
    "multi label learning",
    "similarity learning",
    "statistical relation learning",
    "support vector regression",
    "manifold regularization",
    "decision forest",
    "generalization error",
    "transductive learning",
    "neuro robotic",
    "inductive logic programming",
    "natural language understanding",
    "adaboost",
    "adaptive boosting",
    "incremental learning",
    "random forest",
    "metric learning",
    "neural gas",
    "grammatical inference",
    "support vector machine",
    "multi label classification",
    "conditional random field",
    "multi class classification",
    "mixture of expert",
    "concept drift",
    "genetic programming",
    "string kernel",
    "learning to rank",
    "machine-learned ranking",
    "boosting algorithm",
    "robot learning",
    "relevance vector machine",
    "connectionism",
    "multi kernel learning",
    "graph learning",
    "naive bayes classifier",
    "rule-based system",
    "classification algorithm",
    "graph kernel",
    "rule induction",
    "manifold learning",
    "label propagation",
    "hypergraph learning",
    "one class classifier",
    "intelligent algorithm",
)

In [ ]:
# IPC codes: every symbol starting with one of these prefixes is selected
AI_IPC_CODES = (
    "A63F13/67",
    "G06F8/33",
    "G06F15/18",
    "G06F17/20",
    "G06F17/21",
    "G06F17/27",
    "G06F17/28",
    "G06F19/24",
    "G06K9/66",
    "G06N3/02",
    "G06N3/04",
    "G06N3/06",
    "G06N3/063",
    "G06N3/067",
    "G06N3/08",
    "G06N3/10",
    "G06N5/00",
    "G06N5/02",
    "G06N5/04",
    "G06N7/02",
    "G06N20",
    "G06N20/00",
    "G06N20/10",
    "G06N20/20",
    "G06T1/40",
    "G10L15/06",
    "G10L15/16",
    "G10L15/18",
    "G10L17/04",
    "G10L17/10",
    "G10L17/18",
    "G10L25/30",
    "G16B40",
    "G16B40/00",
    "G16B40/20",
    "G16B40/30",
    "G16C20/70",
    "G16H50/20",
    "H01M8/04992",
)

In [ ]:
# CPC codes: every symbol starting with one of these prefixes is selected
AI_CPC_CODES = (
    "A61B5/7264",
    "A61B5/7267",
    "A63F13/67",
    "B23K31/006",
    "B25J9/161",
    "B25J9/163",
    "B29C66/965",
    "B29C2945/76946",
    "B29C2945/76949",
    "B29C2945/76979",
    "Y10S128/924",
    "Y10S128/925",
    "Y10S706",
)

### Functions

In [1]:
def keyword_condition(terms):
    """OR-condition: any term appears in the title or in the abstract (case-insensitive)."""
    title = func.lower(TLS202_APPLN_TITLE.appln_title)
    abstract = func.lower(TLS203_APPLN_ABSTR.appln_abstract)
    return or_(
        *(title.like(f"%{t.lower()}%") for t in terms),
        *(abstract.like(f"%{t.lower()}%") for t in terms),
    )


def symbol_prefix_condition(symbol_column, codes):
    """OR-condition: the blank-stripped classification symbol starts with one of the codes."""
    symbol = func.replace(symbol_column, " ", "")
    return or_(*(symbol.like(code.replace(" ", "") + "%") for code in codes))


# Base columns shown for every application
APPLN_COLUMNS = (
    TLS201_APPLN.appln_id,
    TLS201_APPLN.appln_auth,
    TLS201_APPLN.appln_nr,
    TLS201_APPLN.appln_kind,
    TLS201_APPLN.appln_filing_date,
)


def query_by_keywords(*columns):
    """Applications whose title or abstract contains an AI keyword."""
    return (
        db.query(*columns)
        .select_from(TLS201_APPLN)
        .outerjoin(TLS202_APPLN_TITLE, TLS201_APPLN.appln_id == TLS202_APPLN_TITLE.appln_id)
        .outerjoin(TLS203_APPLN_ABSTR, TLS201_APPLN.appln_id == TLS203_APPLN_ABSTR.appln_id)
        .filter(keyword_condition(AI_KEYWORDS))
    )


def query_by_ipc(*columns):
    """Applications with at least one IPC symbol in the AI list."""
    return (
        db.query(*columns)
        .select_from(TLS201_APPLN)
        .join(TLS209_APPLN_IPC, TLS201_APPLN.appln_id == TLS209_APPLN_IPC.appln_id)
        .filter(symbol_prefix_condition(TLS209_APPLN_IPC.ipc_class_symbol, AI_IPC_CODES))
    )


def query_by_cpc(*columns):
    """Applications with at least one CPC symbol in the AI list."""
    return (
        db.query(*columns)
        .select_from(TLS201_APPLN)
        .join(TLS224_APPLN_CPC, TLS201_APPLN.appln_id == TLS224_APPLN_CPC.appln_id)
        .filter(symbol_prefix_condition(TLS224_APPLN_CPC.cpc_class_symbol, AI_CPC_CODES))
    )

NameError: name 'TLS201_APPLN' is not defined

In [ ]:
#query for keywords search
q_keywords = query_by_keywords(
    *APPLN_COLUMNS,
    TLS202_APPLN_TITLE.appln_title,
    TLS203_APPLN_ABSTR.appln_abstract,
).distinct()

df_keywords = patstat.df(q_keywords)
df_keywords.head(10)

#query for IPC
q_ipc = query_by_ipc(*APPLN_COLUMNS, TLS209_APPLN_IPC.ipc_class_symbol).distinct()

df_ipc = patstat.df(q_ipc)
df_ipc.head()

#query for CPC
q_cpc = query_by_cpc(*APPLN_COLUMNS, TLS224_APPLN_CPC.cpc_class_symbol).distinct()

df_cpc = patstat.df(q_cpc)
df_cpc.head(10)

In [ ]:
#combined strategy
appln_id = TLS201_APPLN.appln_id.label("appln_id")

ai_ids = (
    query_by_keywords(appln_id)
    .union(query_by_ipc(appln_id), query_by_cpc(appln_id))
    .subquery()
)

q_ai = (
    db.query(*APPLN_COLUMNS, TLS202_APPLN_TITLE.appln_title)
    .select_from(TLS201_APPLN)
    .join(ai_ids, TLS201_APPLN.appln_id == ai_ids.c.appln_id)
    .outerjoin(TLS202_APPLN_TITLE, TLS201_APPLN.appln_id == TLS202_APPLN_TITLE.appln_id)
    .distinct()
    .order_by(TLS201_APPLN.appln_filing_date)
)

df_ai = patstat.df(q_ai)
df_ai.head(10)

# How much does each strategy contribute? (counts of distinct applications)
pd.Series(
    {
        "keywords": df_keywords["appln_id"].nunique(),
        "IPC": df_ipc["appln_id"].nunique(),
        "CPC": df_cpc["appln_id"].nunique(),
        "union (AI set)": df_ai["appln_id"].nunique(),
    },
    name="applications",
)

### Advanced strategies